### ISSUE TITLE
Chapters and Lessons Numbering issue 

### ISSUE THREAD

**Issue by Mohamed-Elmasri** [dhorseman1710/Decrypt-PluralSight-GUI#1]
![image](https://user-images.githubusercontent.com/39469567/118793975-6b9eac00-b899-11eb-97e3-47cd2f966cfc.png)
![image](https://user-images.githubusercontent.com/39469567/118794045-7a855e80-b899-11eb-987d-a6113743b9f7.png)
![image](https://user-images.githubusercontent.com/39469567/118794022-75281400-b899-11eb-8e08-c3ec4c7f802e.png)

Numbers is weird ! 

Thanks for your effort but please fix that 
tested course
https://app.pluralsight.com/library/courses/core-python-big-picture/table-of-contents

**Comment by mrvogiacu** [comment]
@Mohamed-Elmasri can you zip the course and db file so i can test it. For now i don't have account to download the course

**Comment by Mohamed-Elmasri** [comment]
Thanks @mrvogiacu  .. here is the link https://we.tl/t-9sM1ZsuqFX

**Comment by dhorseman1710** [comment]
@Mohamed-Elmasri already fixed at version 1.9.1.
Please download the latest version and try it.
