### ISSUE TITLE
Still Having an Issue 

### ISSUE THREAD

**Issue by TenzenKur** [dhorseman1710/Decrypt-PluralSight-GUI#5]
HI Sir, 

I still have an issue vidoes dont get downloaded only the folders and titles are created can you please reupload the yotube video for me and I can watch the exact steps 

Thanks a bunch!!!!

**Comment by mrvogiacu** [comment]
Can you describt more about your issue? Like step or screenshot
You can watch this video. It's same step with current version (2.0)

https://m.youtube.com/watch?v=EwW_Ni6D8B0

**Comment by TenzenKur** [comment]
Hi Sorry sure, 

I downloaded the repo and I see these files 

![image](https://user-images.githubusercontent.com/85894905/121990961-56476f80-cdbc-11eb-8f59-168759f9be33.png)

Not sure what does the stuff in the Tool do yet 

please note the version of the GUI tool that I am using and its the latest 

![image](https://user-images.githubusercontent.com/85894905/121991025-71b27a80-cdbc-11eb-8481-6a7d75344462.png)

I am going to download the shown course 

![image](https://user-images.githubusercontent.com/85894905/121991161-c35b0500-cdbc-11eb-8631-53c0c2bbbde8.png)

it says the course is downlaoded 

![image](https://user-images.githubusercontent.com/85894905/121991284-fac9b180-cdbc-11eb-87bd-7ba85c663cb0.png)

however, no videos are there its just the folders 

![image](https://user-images.githubusercontent.com/85894905/121991323-103edb80-cdbd-11eb-8a11-1e5c21e5312b.png)

**Comment by mrvogiacu** [comment]
> Hi Sorry sure,
> 
> 
> however, no videos are there its just the folders
> 

The tool folder contains the tool to recovery the video decrypted by wrong version

can you zip and send me the logs folder, the course folder of the error course and the DB file.
You can detect the course by check the course folder, this course have only 1 module and 1 video

**Comment by TenzenKur** [comment]
Hi Sir, 

when I run the POP and browse the course and run for all the versions I get the below error 

![image](https://user-images.githubusercontent.com/85894905/122033865-91629680-cdee-11eb-82b0-ebac7802ef4d.png)

please help what should I do

**Comment by TenzenKur** [comment]
Hi This is what the log file shows 
![image](https://user-images.githubusercontent.com/85894905/122036273-033bdf80-cdf1-11eb-9d14-9a8a1e41a7aa.png)

**Comment by mrvogiacu** [comment]
> Hi Sir,
> 
> when I run the POP and browse the course and run for all the versions I get the below error
> 
> ![image](https://user-images.githubusercontent.com/85894905/122033865-91629680-cdee-11eb-82b0-ebac7802ef4d.png)
> 
> please help what should I do

this is my tool. POP is Pluralsight offline player.

Can you try to replace the **DecryptPluralSightVideosGUI.exe.config** with the attachment file below and try again? And don't forget tell me the result

[DecryptPluralSightVideosGUI.zip](https://github.com/dhorseman1710/Decrypt-PluralSight-GUI/files/6654895/DecryptPluralSightVideosGUI.zip)

**Comment by TenzenKur** [comment]
HI mrvogiacu, 

You did it now its working. can I know what was the issue and what was done to correct this please

**Comment by mrvogiacu** [comment]
> HI mrvogiacu,
> 
> You did it now its working. can I know what was the issue and what was done to correct this please

because your pc don't allow to load DLL dynamic (ExtLibrary.dll). I just add a config to exe config file to allow it.

In the future, if Pluralsight change their algorithm, you can update your POP app => copy file Pluralsight.domain.dll to another folder =>rename it to ExtLibrary.dll => copy and replace it into exe folder and try to decrypt and maybe it work :D

**Comment by TenzenKur** [comment]
Hi mrvogiacu, 

Thanks you for your time and help. I do have some questions on what you said above little confusing when you get time can you help me understand the below.

1. How do I use this tool I tried to browse to the course and execute but gives me error the scresnshot that I showed above 

![image](https://user-images.githubusercontent.com/85894905/122043305-cecc2180-cdf8-11eb-93b1-c84412d57f3d.png)

2. could you please elaborate a little more on this if you could please 
In the future, if Pluralsight change their algorithm, you can update your POP app => copy file Pluralsight.domain.dll to another folder =>rename it to ExtLibrary.dll => copy and replace it into exe folder and try to decrypt and maybe it work :D


Thank you

**Comment by mrvogiacu** [comment]
> Hi mrvogiacu, 
> 
> Thanks you for your time and help. I do have some questions on what you said above little confusing when you get time can you help me understand the below.
> 
> 1. How do I use this tool I tried to browse to the course and execute but gives me error the scresnshot that I showed above 
> 
> ![image](https://user-images.githubusercontent.com/85894905/122043305-cecc2180-cdf8-11eb-93b1-c84412d57f3d.png)
> 
> 2. could you please elaborate a little more on this if you could please 
> In the future, if Pluralsight change their algorithm, you can update your POP app => copy file Pluralsight.domain.dll to another folder =>rename it to ExtLibrary.dll => copy and replace it into exe folder and try to decrypt and maybe it work :D
> 
> 
> Thank you 
> 
> 

1. The tool for someone who decrypt the video by other tool and got error video file. They can use this tool to recovery that error video.

2. In the future. If the pluralsight change their algorithm and this tool can't decrypt the video correctly. You can follow the step above to fix without me 😊

**Comment by TenzenKur** [comment]
Hi mrvogiacu, 

Thank you very much :) your an awesome individual with quick replies and solutions amazing want to be a .Net developer like you one day hehe 

Thank you,

**Comment by mrvogiacu** [comment]
> Hi mrvogiacu, 
> 
> Thank you very much :) your an awesome individual with quick replies and solutions amazing want to be a .Net developer like you one day hehe 
> 
> Thank you, 
> 

Glad to hear it 😊
