### ISSUE TITLE
I can't find the source, only binaries...

### ISSUE THREAD

**Issue by Zafpyr** [dhorseman1710/Decrypt-PluralSight-GUI#7]
I can't find the source, only binaries...

**Comment by dhorseman1710** [comment]
Yes, becuz I push the binary only 😊

**Comment by Zafpyr** [comment]
I got the source code of the project this was forked from and got it working really well. 

Just thought you should know in accordance with the project license, "GNU General Public License v3.0" [link](https://github.com/dhorseman1710/Decrypt-PluralSight-GUI/blob/main/LICENSE), you're required to disclose the source code. 😎👍

Cheers.

**Comment by dhorseman1710** [comment]
1. My tool is free, always free.
2. I don't push the source code becuz maybe the tool will be fixed very fast
3. Can you share me the website you are using to check my tool. My tool don't need connect to any site to run

**Comment by Zafpyr** [comment]
1. Malware is free too and it's everywhere these days. 

2. Hard to trust something on GitHub that has binaries but no source code. 
The decryption methods are in a few of the PluralSight Offline Player's DLLs, why not just utilize the methods in those DLLs? 
Should work as long as the user has PluralSight Offline Player installed, which they need anyway.

3. Virus Total: https://www.virustotal.com/gui/file/5ddc512445b480ca5f0d3c83ee0a39924fabf704d0a272079639c4e2c6a1eda4/relations

**Comment by dhorseman1710** [comment]
1. If I inject the malware into this tool. I don't need to work with this sheet https://docs.google.com/spreadsheets/d/1Lr_fw94rRau7AcOo9Fxc1fBs4R3ANxT4UC7sIvPsb7g/edit?usp=drivesdk
2. As I said, I have already pushed the source code before, and the tool was fixed very quickly. About injecting the POP's DLL, You can check the history version. I have already done it, and it's was fixed.
3. I found it and still checking my source code.

**Comment by dhorseman1710** [comment]
Hi @Zafpyr,
I just check my source code and I found that IP is connecting from NLog, and this IP belongs to Microsoft
