### ISSUE TITLE
not really issue but request

### ISSUE THREAD

**Issue by outty72** [dhorseman1710/Decrypt-PluralSight-GUI#8]
could another button be added 

queue 20 from search result

so can load the queue automated 20 at a time, then 20 more , ...

**Comment by dhorseman1710** [comment]
> could another button be added 
> 
> queue 20 from search result
> 
> so can load the queue automated 20 at a time, then 20 more , ...

I don't understand what do you want?

**Comment by outty72** [comment]
was wondering if could merge the two .exe together and use their search result as a queue.

that would essential eliminate loading 30 at a time.

only other option is edit their exe in IDA Pro and increase the limit of 30 set in the search in 3 places

in their SearchWindow.cs (decompiled with dotPeek)

`

private const int MaximumCoursesUserCanDownload = 30;

bool isDownloadLimitReached = source.Count >= 30;


`

**Comment by dhorseman1710** [comment]
My tool only for decrypt video. If you want to search like their tool, I need the login information, that is the secret information. To be honest, do you want to provide your account and password for a tool public in the internet?

About the 30 course limit of their tool, I know about that, and I think it is good to block someone who want to download and sell the course with my tool.

**Comment by outty72** [comment]
was just asking if could be automated. but since want to access someone seems more likely someone that makes a tool like this is the one selling content.

**Comment by dhorseman1710** [comment]
I don't understand what you mean. I don't sell this tool orr another version of this tool, and I don't sell any course.
